### ISSUE TITLE
html10n.localize(["es.es", "es.mx"]) ignores "es.mx"?

### ISSUE THREAD

**Issue by kenmanheimer** [marcelklehr/html10n.js#13]
If I'm understanding the array argument to `html10n.localize()` correctly, then there's a problem when the first languages code is "es.es". Subsequent entries in the array are overwritten with three "es" entries derived from the "es.es" entry (by [this code](https://github.com/marcelklehr/html10n.js/blob/master/l10n.js#L916-L926)).

This means that, if you use the array to designate a kind of precedence list for language sources to consult, then several of your candidates are stomped.

This behavior won't just happen for "es.es", that's just a handy (and real-world) example.

As I said, I may be misunderstanding the intent of the array argument. The docstring says "An array of lang codes defining fallbacks", which sounds like what I'm thinking. Clarification would be appreciated.

If I am understanding the purpose correctly, then I'd be happy provide an candidate alternative implementation that doesn't stomp the other contents of the array. Please clarify!

**Comment by devgeeks** [comment]
Obviously, this applies equally to variations.. en-US, es-ES, de-DE, etc
