### ISSUE TITLE
plural doesn't work with russian language

### ISSUE THREAD

**Issue by MrZeiden** [marcelklehr/html10n.js#18]
Example:
EN:
"cutPhotos":"Cut {{n}} {[ plural(n) one: photo, other: photos ]} !"
result:
Cut 1 photo!

Ru:
"cutPhotos":"Обрежьте еще {{n}} {[ plural(n) one: фото, other: фото ]} !",

Обрежьте еще !

**Comment by MrZeiden** [comment]
Cool! But in Russian when n=5 other doesn't work...
Обрежьте еще 5 undefined

**Comment by marcelklehr** [comment]
Looks like you need to use the `many` keyword: http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#ru ;)
