### ISSUE TITLE
Cannot call method 'load' of undefined.

### ISSUE THREAD

**Issue by aronrodrigues** [marcelklehr/html10n.js#5]
Version of master branch.

Uncaught TypeError: Cannot call method 'load' of undefined l10n.js:905
(anonymous function) l10n.js:905
asyncForEach l10n.js:729
window.html10n.html10n.build l10n.js:903
window.html10n.html10n.localize l10n.js:701
(anonymous function)

i18n.html

```
<html>
<head>
  <script type="text/javascript" src="js/l10n.js"></script>
  <link rel="localizations" href="i18n.json" type="application/l10n+json"/>
  <script>
html10n.localize('fr');
html10n.on('localized', function() {
  console.log('Localized!')
});
  </script>
</head>
<body>
  <button data-l10n-id="test" title="click me!">This is a test</button>
</body>
</html>
```

i18n.json

```
{
"en": {
  "test": "This is a test",
  "test.title": "click me!"
},
"fr": {
  "test": "Ceci est un test",
  "test.title": "cliquez-moi!"
}
}
```

**Comment by mistermantas** [comment]
You should change the README to document this. I copy pasted it and it didn’t work, that’s not great.
